when:
  - event: push
    branch: master

steps:
  - name: Clone Repository
    image: alpine/git
    commands:
      - git clone https://github.com/GodotOnlineCOM/GodotOnline-P2P-Plugin.git
      - ls

  - name: Install Dependencies & Build
    image: ubuntu
    commands:
      - apt update && apt install -y wget unzip
      - wget https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
      - unzip Godot_v4.4-stable_linux.x86_64.zip -d ./
      - ls
      - pwd
      - chmod +x Godot_v4.4-stable_linux.x86_64
      - ./Godot_v4.4-stable_linux.x86_64 --export-release "Test Server" server.x86_64
      - ls


