when:
  - event: push
    branch: master

steps:
  - name: build
    image: barichello/godot-ci:4.4
    commands:
      - echo "This is the build step"
      - godot --version
      - godot --headless --no-window --export-release "Test" test.x86_64
