pipeline:
  build:
    image: barichello/godot-ci:4.4
    commands:
      - godot --version
      - godot --headless --build-solutions --quit
    when:
      event: [ push, pull_request ]

  test:
    image: barichello/godot-ci:4.4
    commands:
      - godot --headless --quit --test
    when:
      event: [ push, pull_request ]

  export-html5:
    image: barichello/godot-ci:4.4
    commands:
      - mkdir -p exports/html5
      - godot --headless --quit --export-release "HTML5" exports/html5/index.html
      - ls -la exports/html5/
    when:
      event: tag
