when:
  - event: push
    branch: master

steps:
  - name: Build Linux
    image: barichello/godot-ci:4.4
    commands:
      - echo "This is the build step"
      - echo 'export PATH=$PATH:/bin/webrtc' >> ~/.bashrc
      - source ~/.bashrc
      - godot --version
      - godot --headless --no-window --export-release "Linux" /bin/webrtc/server2.x86_64
      - pwd
      - ls
