when:
  - event: push
    branch: master

steps:
  - name: Clone Repository
    image: alpine/git
    commands:
      - git clone https://github.com/GodotOnlineCOM/GodotOnline-P2P-Plugin.git /bin/webrtc
      - cd /bin/webrtc

  - name: Build Godot Project
    image: ubuntu
    commands:
      - ls
      - pwd
      - godot --headless --export-debug "Linux/X11" build/server.x86_64

  - name: Upload Artifacts
    image: alpine
    commands:
      - mv /bin/webrtc/build/server.x86_64 /bin/webrtc
