version: "1"

steps:
  - name: clone-repo
    image: alpine
    commands:
      - apk add --no-cache git
      - git clone https://github.com/GodotOnlineCOM/GodotOnline-P2P-Plugin.git /drone/src/Godot
      - mkdir -p /drone/src/build/linux
      - mkdir -p /drone/src/build/windows
      - mkdir -p /drone/src/build/mac
      - mkdir -p /drone/src/build/web

  - name: export-linux
    image: barichello/godot-ci:3.1.1
    commands:
      - cd /drone/src/Godot
      - godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - test -e ../build/linux/$EXPORT_NAME.x86_64
    when:
      branch: master

  - name: export-windows
    image: barichello/godot-ci:4.4
    commands:
      - cd /drone/src/Godot
      - godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - test -e ../build/windows/$EXPORT_NAME.exe
    when:
      branch: master

  - name: export-mac
    image: barichello/godot-ci:4.4
    commands:
      - cd /drone/src/Godot
      - godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - test -e ../build/mac/$EXPORT_NAME.zip
    when:
      branch: master

  - name: export-web
    image: barichello/godot-ci:4.4
    commands:
      - cd /drone/src/Godot
      - godot -v --path /drone/src/Godot --export "HTML5" ../build/web/index.html
      - test -e ../build/web/index.html
    when:
      branch: master
