when:
  - event: push
    branch: master

steps:
  - name: Clone Repository
    image: alpine/git
    commands:
      - git clone https://github.com/GodotOnlineCOM/GodotOnline-P2P-Plugin.git

  - name: Install Dependencies
    image: ubuntu
    commands:
      - apt update && apt install -y wget unzip
      - wget https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
      - unzip Godot_v4.4-stable_linux.x86_64.zip -d ./
      - chmod +x Godot_v4.4-stable_linux.x86_64
      - apt update && apt install -y libfontconfig1
      - apt update && apt install -y wget unzip libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
      - wget https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz

      
  - name: Build
    image: ubuntu
    commands:
      - ./Godot_v4.4-stable_linux.x86_64 --headless --no-window --export-release "Test Server" server.x86_64
      - ls


